# Generated by Django 6.0.2 on 2026-02-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('iconColor', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fullname'],
            },
        ),
    ]
